### ISSUE TITLE
v16.0.0-beta.18 & Git Plugin - Edge Case

### ISSUE THREAD

**Issue by zaripych** [semantic-release/git#130]
I'm setting up a workflow as described here: https://github.com/semantic-release/semantic-release/blob/beta/docs/usage/workflow-configuration.md 

I have two pre-release branches:

- `dev`
- `test`

`test` was ahead of `dev` with a few *fix* commits. In addition to those manual commits, as a result of using `semantic-release/git` plugin, the latest commit in the `test` branch was done by `semantic-release-bot` and contained `[skip ci]` text in commit message.

After merging `test` to `dev` the release process in `dev` branch has failed. This happened because the tip of the `dev` was ahead of the commit that Travis checked out. It was the `git` plugin that failed. It failed because of the classic "you should pull first" git error. Travis ignored the latest commit done by `semantic-release/git` plugin in `test` branch. I presume it ignored it because of the `[skip ci]` message. 

This probably can be easily fixed by removing `[skip ci]` from the commit message template in the `semantic-release/git` plugin, and then using `if` condition somewhere inside `.travis.yml`.

I believe that the documentation of the `git` plugin should mention that edge case somewhere. Or maybe even stop suggesting usage of `[skip ci]`. Otherwise the plugin should pull ... which I think might lead to other kind of problems.

### Config
```
module.exports = {
  branches: [
    //
    '+([1-9])?(.{+([1-9]),x}).x',
    { name: 'release' },
    { name: 'master', channel: 'dev', prerelease: true },
    { name: 'test', prerelease: true },
  ],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    [
      '@semantic-release/npm',
      {
        npmPublish: false,
        tarballDir: './',
      },
    ],
    [
      '@semantic-release/git',
      {
        assets: ['package.json'],
        message:
          'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
      },
    ],
    [
      '@semantic-release/github',
      {
        assets: [
          {
            path: ['package-*.tgz'],
            label: 'Build',
          },
        ],
      },
    ],
  ],
};
```
### Travis
```
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '10'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
    - stage: test, build and deploy
      script:
        - yarn build
      deploy:
        - provider: script
          script:
            - yarn semantic-release
          skip_cleanup: true
          on:
            branch:
              - master
              - dev
              - test
```
### Versions in `package.json`:
```
...
  "@semantic-release/git": "7.1.0-beta.3",
  "semantic-release": "16.0.0-beta.18"
...
```
### Steps
1. `git checkout -b dev`
1. `git push origin`
1. `git checkout -b test`
1. `git commit -m 'fix: fixes this or that'`
1. `git push origin`
1. ⏲ wait for release from `test` branch
1. `git checkout dev`
1. `git merge origin/test`
1. `git push origin `
1. ❗ Latest push to `test` would fail to produce new release with error similar to:
```
error: failed to push some refs to XXX
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
```
