### ISSUE TITLE
Commit all the changes behavior 

### ISSUE THREAD

**Issue by phun601** [semantic-release/git#141]
Sorry for being obvious, I have read #107 and  the documentation on `assets`, but still don't get it.

I am looking for some generic solution for versions update (for example, several files with version reference). I've tried to use `@semantic-release/exec` + `@semantic-release/git` but as a result, there are a huge number of files included for commit (which is mostly `node_modules`).

My configuration is
```yaml
branch: master
tagFormat: v${version}
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/changelog"
    -   - "@semantic-release/git"
        - message: "docs(changelog): update changelog\n\n[skip ci]"
    -   - "@semantic-release/exec"
        - prepareCmd: "./semver-bump ${nextRelease.version}"
    -   - "@semantic-release/git"
        - assets:
            - "**/*"
          message: "chore(release): v${nextRelease.version} release\n\n[skip ci]"
    - "@semantic-release/release-notes-generator"
    - "@semantic-release/github"
```

When I am using `assets` option I am expecting to include only files related to a repository, and not the `node_modules`. Am I missing something?
How can I add only the files changed/added to my repository, without explicitly specifying `assets` with all the files I wish to update?
