### ISSUE TITLE
[question] skip-ci

### ISSUE THREAD

**Issue by linceaerian** [semantic-release/git#201]
Hello Maintainers,

I'm currently starting to use your useful tool to push automatically the Changelog in one of my repos.
However I'm wondering about the "best" practice to follow.

I defined my workflow as such,

* commit with angular syntax
* semantic-release will detect it
* sematic-release / changelog generate changelog
* semantic-release / git push changelog
* semantic-release / gitlab generate tag + release
* in case of version tag detected for dev build ci start deploy on dev
* in case of version tag detected for master, build ci start deploy on prod

Except that with default setting it do the following:

![image](https://user-images.githubusercontent.com/1318470/76656587-3e0cf300-6570-11ea-82ff-a37019581ada.png)

It skip the CI on dev (good), then release on tag with last commit aaaand skip deploy ci.
The only way I found to avoid that is to remove the "skip-ci" from message which gives:

![image](https://user-images.githubusercontent.com/1318470/76657010-25e9a380-6571-11ea-80a7-8cb22bb8d513.png)

Except it 're-execute' the semantic-release each time on main branch (dev/master).

Is it the "best" way I can do ?
Would you kindly give any advice ? :)
 
Thanks in advance !

**Comment by pvdlg** [comment]
semantic-release will do nothing on build triggered by the tag.
The best practice is to configure your CI to not trigger a build on a tag creation.

**Comment by giannaccio** [comment]
sorry for the inexperience, but I would like to build and deploy my product once the version is determined. I thought the tag was a great place to do this task

**Comment by gustavoleitao** [comment]
> sorry for the inexperience, but I would like to build and deploy my product once the version is determined. I thought the tag was a great place to do this task

Same problem here.

**Comment by bullettoothaxe** [comment]
> > sorry for the inexperience, but I would like to build and deploy my product once the version is determined. I thought the tag was a great place to do this task
> 
> Same problem here.

the same, in gitlab ci `CI_COMMIT_TAG` allowed only on *tags*

**Comment by bullettoothaxe** [comment]
@pvdlg maybe we already can turn off skipping on tag bumping?

**Comment by evanrich** [comment]
regarding turning off the "skip ci" comment,  You could do a 
```
only:
  - master
```
on your push to prod stage, no?

**Comment by linceaerian** [comment]
Hello all,

Just in case it helps, here what I finished by doing on my side:
```
stages:
- release

.semantic-release:
  image: node:12
  stage: release
  only:
    refs:
    - master
    - dev
    # This matches maintenance branches
    - /^(([0-9]+)\.)?([0-9]+)\.x/
    # This matches pre-releases
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/ 
  script:
    - export GITLAB_URL=$CI_SERVER_URL
    - export GITLAB_TOKEN=$CI_API_TOKEN
    - npm install @semantic-release/gitlab
     #- npm install @semantic-release/git # Cause conflict
     #- npm install @semantic-release/changelog #  Cause conflict
    - npx semantic-release --debug

semantic-release:
  extends: .semantic-release

```

With releaserc configuration:

```
{
  "plugins": [
    ["@semantic-release/commit-analyzer", {
      "preset": "angular",
      "releaseRules": [
        {"type": "docs", "scope":"README", "release": "patch"},
        {"type": "feat", "scope":"progress", "release": "patch"},
        {"type": "feat", "scope":"major", "release": "major"}
      ],
      "parserOpts": {
        "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES"]
      }
    }],
    "@semantic-release/release-notes-generator",
    "@semantic-release/gitlab"
  ],
  "branches": [
	  "master",
          "+([0-9])?(.{+([0-9]),x}).x",
	  { "name": "dev", "prerelease": "dev"}
  ]
}
```

Regards
