### ISSUE TITLE
configure semantic-release to use an administrator user

### ISSUE THREAD

**Issue by guiaramos** [semantic-release/git#210]
Guys how to "configure semantic-release to use an administrator user"?

**Comment by olance** [comment]
Might be a bit late, but here you have some more information: [Pushing package.json to a master branch](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md#pushing-packagejson-changes-to-a-master-branch) (**do read and consider the security concerns this raises** )

You'll have to [generate a personal access token](https://github.com/settings/tokens) for your admin account and set it up in your project's secrets at `https://github.com/<username>/<project name>/settings/secrets/actions`

**Comment by OopsYao** [comment]
You can just use the SSH credential to bypass the GitHub branch protection. Add a deploy key to the GitHub repo and in the release section of the workflow file, before semantic release
```yaml
- name: Checkout
  uses: actions/checkout@v2.3.4
  with:
    ssh-key: ${{ secrets.SSH_PRIVATE_KEY }} # Your private key
```
