### ISSUE TITLE
Adding package.json to git assets does not result in the file being pushed back to repo

### ISSUE THREAD

**Issue by james-kontralto** [semantic-release/git#321]
## Current behavior

The following configuration results in the changelog being pushed back to the target branch, but not `package.json`.

```
prepare:
  - path: '@semantic-release/changelog'
  - path: '@semantic-release/git'
    message: 'RELEASE: ${nextRelease.version}'
    assets: ['CHANGELOG.md', 'package.json']
```

The CI logs indicate the new version is being written to `package.json`, and I'm hoping to get that pushed back upstream so the version shown in the repo is correct.

## Expected behavior

`package.json` should be pushed to the repo along with `CHANGELOG.md`.

## Environment

- **semantic-release** version: 18.0.1
- CI environment: GitLab CI
- Plugins used: changelog, commit-analyzer, exec, git, gitlab, npm, release-notes-generator
- **semantic-release** configuration: https://gitlab.com/james-kontralto/semantic-release-test/-/blob/main/.releaserc.yml
- CI logs: https://gitlab.com/james-kontralto/semantic-release-test/-/jobs/1905701383

Also check out the release commit, it has `CHANGELOG.md` changes but not `package.json`:  https://gitlab.com/james-kontralto/semantic-release-test/-/commit/fcfe8f8311ff5443ecb4b7bd2bc9f37a7fb0e80b
