### ISSUE TITLE
How to push the new package version?

### ISSUE THREAD

**Issue by jtuchel** [semantic-release/git#323]
**What I want to do**

Based on the FAQ

https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package.jsons-version-not-updated-in-my-repository

I want to update the package.json version number on a new release.

---

**What I did**

- Create a new empty private Github repository for an organization `temp` with a *README.md* and *.gitignore* for node 
- Clone the repository
- Fix the first commit message via git `rebase -i --root` and change it to `feat: initial commit`
- Create a package.json with the content

```json
{
  "name": "temp",
  "version": "0.0.0-development",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/my-organization/temp.git"
  }
}
```

- Setup semantic-release

```shell
npm install semantic-release -D
npm install @semantic-release/git -D
npm install @semantic-release/changelog -D
```

- Create a *.releaserc.json*

```json
{
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      "@semantic-release/git"
    ]
}
```

- Create a new Github workflow *release.yml*

```yml
name: Release on push on main branch

on:
  push:
    branches:
      - main

jobs:
  release-on-push-on-main-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches main
```

- Commit everything with the message `feat: next commit`
- Force push to origin

---

**The problem**

The *package.json* file won't get updated by the semantic-release-bot.
Even after modifying the *README.md* file and pushing with `feat: this should trigger a new release`.

![image](https://user-images.githubusercontent.com/92626738/147553582-2552fc0b-bf24-4fa8-b4ec-d7ecce2bc769.png)

How can I tell semantic-release to push the new package version?
