### ISSUE TITLE
How to set commit author?

### ISSUE THREAD

**Issue by OfficialCRUGG** [semantic-release/git#419]
Hey there,

I am having trouble setting the actual commit author account.

My GitHub Workflow Step is set up like this:

```yaml
- name: Release
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    GIT_AUTOR_NAME: "BlazingWorks CI"
    GIT_AUTOR_EMAIL: "hey@blazing.works"
    GIT_COMMITTER_NAME: "BlazingWorks CI"
    GIT_COMMITTER_EMAIL: "hey@blazing.works"
  run: pnpm semantic-release
```

The commits created through this look like this:

![image](https://user-images.githubusercontent.com/25248999/218275112-f08f0c5a-7642-44d0-87da-f40f6e87cd30.png)
