### ISSUE TITLE
Adding option to disable the push to the release branch. bug with the package.json having wrong version after tag

### ISSUE THREAD

**Issue by kopax** [semantic-release/git#51]
I am having troubles with semantic-release and GitLab.

We are doing stages in our GitLab-ci are:

- build
- test
- release
- deploy

Trouble is happening between **release** and **deploy**.

**release** is in charge with `@semantic-release/npm` and `@semantic-release/gitlab` to release to npm and GitLab.

**deploy** is in charge to build the documentation with it's own tool and to release the documentation with Gitlab page.

I have constraints: 

- deploy MUST have the release version from semantic-release (documentation use placeholder and will replace it)
- `@semantic-release/git` can't be used to push the version as it will produce a failure on deploy job (reason: https://gitlab.com/gitlab-org/gitlab-ce/issues/34899 , short story: deploy job needs to be run from `HEAD` in order to be able to deploy it's artifact. So it will fail because `@semantic-release/git` try to also push to the release branch and there is no way to disable that.

This is how we build our documentation:

```yml
release:
  stage: release
  script:
    - npx semantic-release
  dependencies:
    - build
  only:
    - master
  tags:
    - docker

pages:
  stage: deploy
  script:
    - git fetch --tags && git reset HEAD --hard
    # This is how I retrieve the release version, I haven't found a better way, please let me know if you see one
    - PACKAGE_VERSION=$(git describe --tags | awk -F '-' '{print $1}')
    # we use the tags, as we cannot use @semantic-release/git cause it will break the artifact deployement
    - git checkout refs/tags/${PACKAGE_VERSION}
    # this version is outdated, because disabling the `@semantic-release/git` plugin will not only disable the version push on the release branch, but also produce a wrong version with a wrong version number in its tag
    - PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - npm install
    # Replace variables
    - npx rollup-umd-scripts doc variable PACKAGE_NAME=${PACKAGE_NAME}
    - npx rollup-umd-scripts doc variable PACKAGE_PEERS="$(npx rollup-umd-scripts peer npm-install-cmd)"
    - npx rollup-umd-scripts doc variable PACKAGE_VERSION=${PACKAGE_VERSION}
    - npx rollup-umd-scripts doc variable NODE_VERSION=${NODE_VERSION}
    - npx rollup-umd-scripts doc variable NPM_VERSION=${NPM_VERSION}
    - npx rollup-umd-scripts doc variable CI_REPOSITORY_URL=${REPOSITORY_SSH_URL}
    - npx rollup-umd-scripts doc variable CI_PROJECT_URL=${CI_PROJECT_URL}
    - npx rollup-umd-scripts doc variable CI_PROJECT_NAMESPACE=${CI_PROJECT_NAMESPACE}
    - npx rollup-umd-scripts doc variable CI_PROJECT_NAME=${CI_PROJECT_NAME}
    - npx rollup-umd-scripts doc variable IMG_SHIELD_PUBLISHING=$(npx rollup-umd-scripts publish status --badge)
    - npm run styleguide:build
  artifacts:
    paths:
    - public
  only:
    - master
  tags:
    - docker
```

I got a `refs/tags/v1.1.5` tagger by semantic release and the version in the `package.json` is `1.1.4`, I think this is kind of a bug.

Can we consider adding an option to disable the push to the release branch?
