### ISSUE TITLE
Can `@semantic-release/git` push to protected branches using a deploy key (SSH) on gitlab (self hosted)?

### ISSUE THREAD

**Issue by siddjellali** [semantic-release/git#530]
Hi,  

I'm trying to use `@semantic-release/git` to push changes to a **protected branch** in my GitLab instance (self-hosted). I have configured a **deploy key (SSH)** with write access, but the push fails.  

### Setup  
- **GitLab:** Self-hosted  
- **Authentication:** SSH deploy key  
- **Branch protection:** Enabled (push restrictions)  - development.

Does @semantic-release/git support pushing to protected branches when using an SSH deploy key? If not, is there a recommended workaround?

```yaml
semantic-release:
  stage: $[[ inputs.stage ]]
  image: node:22-bookworm
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  before_script:
    - eval "$(ssh-agent -s)"
    - chmod 400 "$DEPLOY_TOKEN_PRIVATE"
    - ssh-add "$DEPLOY_TOKEN_PRIVATE"
    - mkdir -p ~/.ssh
    - git config --global user.email "ia-agent@xxxxxx.fr"
    - git config --global user.name "IA Agent"
    - | 
      cat <<EOF > .releaserc.json
      {
        "branches": ["development"],
        "repositoryUrl": "git@git.xxxxxxxx.com:${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git",
        "tagFormat": "\${version}",
        "plugins": [
          "@semantic-release/commit-analyzer",
          "@semantic-release/release-notes-generator",
          ["@semantic-release/git", {
            "assets": ["**"],
            "message": "🔖 chore(release): \${nextRelease.version}\n\n\${nextRelease.notes}"
          }]
        ]
      }
      EOF
    - cat .releaserc.json
    - npm install --save-dev semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator
  script:
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == 'development'
      when: always
```

```
[12:57:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:57:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 111 commits complete: patch release
[12:57:37 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[12:57:37 PM] [semantic-release] › ℹ  The next release version is 1.33.8
[12:57:37 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:57:37 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:57:37 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[12:57:37 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 8303 file(s) to commit
[12:57:42 PM] [semantic-release] › ✘  Failed step "prepare" of plugin "@semantic-release/git"
[12:57:42 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push --tags [https://gitlab-ci-token:[secure]@git.xxxxx.com/appl/databases/sql.git](https://gitlab-ci-token:%5Bsecure%5D@git.xxxxx.com/appl/databases/sql.git) HEAD:development
remote: GitLab: You are not allowed to push code to protected branches on this project.
To https://git.xxxxx.com/appl/databases/sql.git
 ! [remote rejected] HEAD -> development (pre-receive hook declined)
error: failed to push some refs to 'https://git.xxxxx.com/appl/databases/sql.git'
    at makeError (/builds/appl/databases/sql/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/builds/appl/databases/sql/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async push (/builds/appl/databases/sql/node_modules/@semantic-release/git/lib/git.js:51:3)
    at async module.exports (/builds/appl/databases/sql/node_modules/@semantic-release/git/lib/prepare.js:69:5)
    at async prepare (/builds/appl/databases/sql/node_modules/@semantic-release/git/index.js:28:3)
    at async validator (file:///builds/appl/databases/sql/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///builds/appl/databases/sql/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async file:///builds/appl/databases/sql/node_modules/semantic-release/lib/plugins/pipeline.js:32:5
    at async pluginsConfigAccumulator.<computed> [as prepare] (file:///builds/appl/databases/sql/node_modules/semantic-release/lib/plugins/index.js:87:11) {
  shortMessage: 'Command failed with exit code 1: git push --tags [https://gitlab-ci-token:[secure]@git.xxxxx.com/appl/databases/sql.git](https://gitlab-ci-token:%5Bsecure%5D@git.xxxxx.com/v/databases/sql.git) HEAD:development',
  command: 'git push --tags [https://gitlab-ci-token:[secure]@git.xxxxx.com/appl/databases/sql.git](https://gitlab-ci-token:%5Bsecure%5D@git.xxxxx.com/appl/databases/sql.git) HEAD:development',
  escapedCommand: 'git push --tags "[https://gitlab-ci-token:[secure]@git.xxxxx.com/appl/databases/sql.git](https://gitlab-ci-token:%5Bsecure%5D@git.xxxxx.com/appl/databases/sql.git)" "HEAD:development"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: GitLab: You are not allowed to push code to protected branches on this project.\n' +
    'To https://git.xxxxx.com/appl/databases/sql.git\n' +
    ' ! [remote rejected] HEAD -> development (pre-receive hook declined)\n' +
    "error: failed to push some refs to 'https://git.xxxxx.com/appl/databases/sql.git'",
  failed: true,
  timedOut: [secure],
  isCanceled: [secure],
  killed: [secure],
  pluginName: '@semantic-release/git'
}
Error: Command failed with exit code 1: git push --tags [https://gitlab-ci-token:[secure]@git.xxxxx.com/appl/databases/sql.git](https://gitlab-ci-token:%5Bsecure%5D@git.xxxxx.com/appl/databases/sql.git) HEAD:development
remote: GitLab: You are not allowed to push code to protected branches on this project.
To https://git.xxxxx.com/appl/databases/sql.git
 ! [remote rejected] HEAD -> development (pre-receive hook declined)
error: failed to push some refs to 'https://git.xxxxx.com/appl/databases/sql.git'
    at makeError (/builds/appl/databases/sql/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/builds/appl/databases/sql/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async push (/builds/appl/databases/sql/node_modules/@semantic-release/git/lib/git.js:51:3)
    at async module.exports (/builds/appl/databases/sql/node_modules/@semantic-release/git/lib/prepare.js:69:5)
    at async prepare (/builds/appl/databases/sql/node_modules/@semantic-release/git/index.js:28:3)
    at async validator (file:///builds/appl/databases/sql/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///builds/appl/databases/sql/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async file:///builds/appl/databases/sql/node_modules/semantic-release/lib/plugins/pipeline.js:32:5
    at async pluginsConfigAccumulator.<computed> [as prepare] (file:///builds/appl/databases/sql/node_modules/semantic-release/lib/plugins/index.js:87:11) {
  shortMessage: 'Command failed with exit code 1: git push --tags [https://gitlab-ci-token:[secure]@git.xxxxx.com/appl/databases/sql.git](https://gitlab-ci-token:%5Bsecure%5D@git.xxxxx.com/appl/databases/sql.git) HEAD:development',
  command: 'git push --tags [https://gitlab-ci-token:[secure]@git.xxxxx.com/appl/databases/sql.git](https://gitlab-ci-token:%5Bsecure%5D@git.xxxxx.com/appl/databases/sql.git) HEAD:development',
  escapedCommand: 'git push --tags "[https://gitlab-ci-token:[secure]@git.xxxxx.com/appl/databases/sql.git](https://gitlab-ci-token:%5Bsecure%5D@git.xxxxx.com/appl/databases/sql.git)" "HEAD:development"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: GitLab: You are not allowed to push code to protected branches on this project.\n' +
    'To https://git.xxxxx.com/appl/databases/sql.git\n' +
    ' ! [remote rejected] HEAD -> development (pre-receive hook declined)\n' +
    "error: failed to push some refs to 'https://git.xxxxx.com/appl/databases/sql.git'",
  failed: true,
  timedOut: [secure],
  isCanceled: [secure],
  killed: [secure],
  pluginName: '@semantic-release/git'
}

Cleaning up project directory and file based variables
ERROR: Job failed: command terminated with exit code 1
```

Thanks in advance! 🚀
